export let emptyEmpresaUser = {
    id: null,
    user: {
      id: null,
      name: "",
      email: "",
    },
    empresa: {
      id: null,
      ruc: "",
      nombre: "",
      direccion: "",
      ciudad: {
        id: null,
        nombre: "",
        provincia: {
          id: null,
          nombre: "",
        },
      },
      telefono: "",
      email: "",
      porcentajeIVA: null,
    },
}
export let emptyProducto = {
  id: null,
  codigo: "",
  nombre: "",
  precioVenta: "",
  stockMin: "",
  stockMax: "",
  stock: "",
  controlaStock: false,
  aplicaIva: false,
  empresa: {
    id: null,
  },
};
export let emptyTecnico = {
  id: null,
  cedula: "",
  nombre: "",
  apellido: "",
  email: "",
  telefono: "",
  direccion: "",
  ciudad: {
    id: null,
    nombre: "",
    provincia: {
      id: null,
      nombre: "",
    },
  },
  empresa: {
    id: null,
    ruc: "",
    nombre: "",
    direccion: "",
    ciudad: {
      id: null,
      nombre: "",
      provincia: {
        id: null,
        nombre: "",
      },
    },
    telefono: "",
    email: "",
    porcentajeIVA: "",
  },
};
export let emptyDetalleOrdenServicio = {
  id: null,
  orden_servicio: {},
  cantidad: "",
  producto: {},
  descripcion: "",
  precio_unitario: null,
  descuento: null,
  porcentaje_IVA: null,
  valor_IVA: null,
  total: null,
  estado_orden_servcio: {},
};
export let emptyCliente = {
  id: null,
  nombres: "",
  apellidos: "",
  dni: "",
  direccion: "",
  telefono: "",
  celular: "",
  email: "",
  estado: null,
};
export let emptyOrdenServicio = {
  id: null,
  numero_orden: "",
  empresa: {
    id: null,
    ruc: "",
    nombre: "",
    direccion: "",
    ciudad: "",
    telefono: "",
    email: "",
    porcentajeIVA: null,
  },
  cliente: {
    id: null,
    nombres: "",
    apellidos: "",
    dni: "",
    direccion: "",
    telefono: "",
    celular: "",
    email: "",
    estado: "",
  },
  fecha_emision: "",
  estado_orden_servicio: {
    id: null,
    state: "",
    empresa: {
      id: null,
      ruc: "",
      nombre: "",
      direccion: "",
      ciudad: "",
      telefono: "",
      email: "",
      porcentajeIVA: null,
    },
  },
  sub_total_con_IVA: "",
  sub_total_sin_IVA: "",
  tecnico: {
    id: null,
    cedula: null,
    nombre: "",
    apellido: "",
    email: "",
    telefono: "",
    direccion: "",
  },
  descuento: "",
  valor_IVA: "",
  total: "",
  observaciones: "",
  diagnostico_recepcion: "",
  diagnostico_tecnico: "",
};
